spring.application.name=cesmar
# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/polocesmar
spring.datasource.username=postgres
spring.datasource.password=bini
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA/Hibernate
# 'update' cria ou atualiza as tabelas no DB com base nas Entidades Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração do Server
server.port=8081